### ISSUE TITLE
Still Maintained?

### ISSUE THREAD

**Issue by Ryamonster10** [Robinson664/bemu#5]
Is this project still maintained?

**Comment by datatalking** [comment]
I was going to ask this myself, was looking for something like this but with python.

@Ryamonster10, @Robinson664 Rya This looks to be a deprecated repo, we are maintaining it here with pandas dataframe in python.
https://github.com/MatthewGilbert/pdblp

**Comment by Robinson664** [comment]
I don't maintain this anymore
